### ISSUE TITLE
Can you please add the icon of input-method ?

### ISSUE THREAD

**Issue by mcjoeng** [obnosim/velours#2]

**Comment by obnosim** [comment]
I cannot find it in the documentation or in default themes. Do you know a theme that provides it? I'm not sure what it is exactly.

**Comment by mcjoeng** [comment]
openSUSE-plasma-theme provides it. It is named "input.svgz"
Look at this I open this file with Inkscape. The objoect properties shows "input-keyboard"
![snapshot3](https://cloud.githubusercontent.com/assets/10485304/9923560/0acf9fb4-5d29-11e5-8ef7-53eb054b6585.png)

**Comment by obnosim** [comment]
Ok, I see what you mean! I'll make it a priority. Thanks!

**Comment by obnosim** [comment]
The input icon was just added to the theme. I might revise it later as I'm not completely happy with the design, but I hope it's good enough for now.
