### ISSUE TITLE
License

### ISSUE THREAD

**Issue by beojan** [obnosim/velours#4]
This is really more a request rather than a bug report. Would you mind switching to BY-SA instead of BY-NC-SA? The former allows combining elements of this theme with parts of a GPL licensed theme, while the latter doesn't.

**Comment by obnosim** [comment]
I didn't know about that, thanks for letting me know. Yes, this is something I could definitely consider.

Is it for your own needs or is it for a hypothetical situation?

**Comment by beojan** [comment]
Sort of both. I'm combining parts of Velours with other themes (Papirus, Produkt), and I might put the result on Github later.

**Comment by obnosim** [comment]
There you go.

**Comment by beojan** [comment]
Thank you. You should probably change it in `metadata.desktop` too though.

**Comment by obnosim** [comment]
Whoops, done.
